/* ************** LEVANTAMENTO DE DADOS - PREMIA FUNCIONARIOS */
SELECT 

-- CAMPOS DEFAULT
PAR.CODPARC, 
PAR.RAZAOSOCIAL, 
PAR.CODVEND, 

-- CAMPOS 1 PREMIO
GRP_RMD_PRM,
OBJ_RMD_PRM,
NVL(FAT_RMD_PRM, 0) AS FAT_RMD_PRM,
(CASE 
    WHEN NVL(FAT_RMD_PRM, 0) < OBJ_RMD_PRM THEN OBJ_RMD_PRM - NVL(FAT_RMD_PRM, 0)
ELSE
    (CASE WHEN NVL(FAT_RMD_PRM, 0) > OBJ_RMD_PRM THEN 0 END) 
END) AS QNT_FALTA_RMD_PRM, 

-- CAMPOS 1 CRUZEIRO
GRP_RMD_CRU, 
NVL(FAT_RMD_CRU, 0) AS FAT_RMD_CRU,
RANK_RMD_CRU, 

-- CAMPOS 2 PREMIO 
GRP_TIGRE_PRM, 
OBJ_TIGRE_PRM, 
NVL(FAT_TIGRE_PRM, 0) AS FAT_TIGRE_PRM, 
(CASE 
    WHEN NVL(FAT_TIGRE_PRM, 0) < OBJ_TIGRE_PRM THEN OBJ_TIGRE_PRM - NVL(FAT_TIGRE_PRM, 0)
ELSE
    (CASE WHEN NVL(FAT_TIGRE_PRM, 0) > OBJ_TIGRE_PRM THEN 0 END) 
END) AS QNT_FALTA_TIGRE_PRM, 

-- CAMPOS 2 RESORT 
GRP_TIGRE_RST, 
NVL(FAT_TIGRE_RST, 0) AS FAT_TIGRE_RST, 
RANK_TIGRE_RST, 

-- CAMPOS 2 TORNEIRAS E PINCEIS  
GRP_TIGRE_CC, 
NVL(FAT_TIGRE_CC, 0) AS FAT_TIGRE_CC, 
RANK_TIGRE_CC 

FROM TGFPAR PAR 

LEFT JOIN 
(
/* **************  APURACAO 1 PREMIO              */
SELECT

C.CODPARC AS CODPARC_RMD_PRM,
O.GRUPOPARTIC AS GRP_RMD_PRM,
O.OBJ1 AS OBJ_RMD_PRM,
SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) AS FAT_RMD_PRM

FROM TGFCAB C, TGFTOP T, AD_OBJETIVOSRMD O

WHERE 
TRUNC(C.DTFATUR) BETWEEN '01/05/2019' AND '30/09/2019'   /* ALTERAR PERIODO DA CAMPANHA  */
AND T.GOLSINAL=-1
AND C.STATUSNOTA='L'
AND O.CODCAMP=18 

AND O.CODPARTIC=C.CODPARC
AND T.CODTIPOPER=C.CODTIPOPER
AND T.DHALTER=C.DHTIPOPER

GROUP BY 
C.CODPARC,
O.GRUPOPARTIC,
O.OBJ1 
/* **************  FIM: APURACAO 1 PREMIO         */
) ON CODPARC_RMD_PRM=PAR.CODPARC 

LEFT JOIN 
(
/* **************  APURACAO 1 CRUZEIRO            */
SELECT 

C.CODPARC AS CODPARC_RMD_CRU, 
O.GRUPOPARTIC AS GRP_RMD_CRU, 
SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) AS FAT_RMD_CRU, 
DENSE_RANK() OVER (PARTITION BY O.GRUPOPARTIC ORDER BY SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) DESC )  AS RANK_RMD_CRU 

FROM TGFCAB C, TGFTOP T, AD_OBJETIVOSRMD O 

WHERE 
TRUNC(C.DTFATUR) BETWEEN '01/05/2019' AND '30/09/2019'   /* ALTERAR PERIODO DA CAMPANHA  */
AND T.GOLSINAL=-1
AND C.STATUSNOTA='L'
AND O.CODCAMP=18 

AND O.CODPARTIC=C.CODPARC 
AND T.CODTIPOPER=C.CODTIPOPER 
AND T.DHALTER=C.DHTIPOPER 

GROUP BY 
C.CODPARC,
O.GRUPOPARTIC 
/* **************  FIM: APURACAO 1 CRUZEIRO       */
) ON CODPARC_RMD_CRU=PAR.CODPARC 

LEFT JOIN 
(
/* **************  APURACAO 2 PREMIO            */
SELECT 

C.CODPARC AS CODPARC_TIGRE_PRM, 
O.GRUPOPARTIC AS GRP_TIGRE_PRM, 
O.OBJ1 AS OBJ_TIGRE_PRM, 
SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) AS FAT_TIGRE_PRM 

FROM TGFCAB C, TGFPAR P, TGFTOP T, AD_OBJETIVOSRMD O 

WHERE 
P.FORNECEDOR = 'S' 
AND P.RAZAOSOCIAL LIKE '%TIGRE%' 
AND TRUNC(C.DTFATUR) BETWEEN '01/05/2019' AND '30/09/2019'   /* ALTERAR PERIODO DA CAMPANHA  */
AND T.GOLSINAL=-1
AND C.STATUSNOTA='L'
AND O.CODCAMP=18 

AND O.CODPARTIC=C.CODPARC
AND T.CODTIPOPER=C.CODTIPOPER
AND T.DHALTER=C.DHTIPOPER

GROUP BY 
C.CODPARC,
O.GRUPOPARTIC,
O.OBJ1 
/* **************  FIM: APURACAO 2 PREMIO       */
) ON CODPARC_TIGRE_PRM=PAR.CODPARC 

LEFT JOIN 
(
/* **************  APURACAO 2 RESORT            */
SELECT 

C.CODPARC AS CODPARC_TIGRE_RST, 
O.GRUPOPARTIC AS GRP_TIGRE_RST, 
SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) AS FAT_TIGRE_RST, 
DENSE_RANK() OVER (PARTITION BY O.GRUPOPARTIC ORDER BY SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) DESC )  AS RANK_TIGRE_RST

FROM TGFCAB C, TGFPAR P, TGFTOP T, AD_OBJETIVOSRMD O 

WHERE 
P.FORNECEDOR = 'S' 
AND P.RAZAOSOCIAL LIKE '%TIGRE%' 
AND TRUNC(C.DTFATUR) BETWEEN '01/05/2019' AND '30/09/2019'   /* ALTERAR PERIODO DA CAMPANHA  */
AND T.GOLSINAL=-1
AND C.STATUSNOTA='L'
AND O.CODCAMP=18 
 
AND O.CODPARTIC=C.CODPARC 
AND T.CODTIPOPER=C.CODTIPOPER 
AND T.DHALTER=C.DHTIPOPER 

GROUP BY 
C.CODPARC, 
O.GRUPOPARTIC 
/* **************  FIM: APURACAO 2 RESORT       */
) ON CODPARC_TIGRE_RST=PAR.CODPARC 

LEFT JOIN
(
/* ************  APURACAO 2 TORNEIRAS E PINCEIS */
SELECT 

C.CODPARC AS CODPARC_TIGRE_CC, 
O.GRUPOPARTIC AS GRP_TIGRE_CC, 
SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) AS FAT_TIGRE_CC, 
DENSE_RANK() OVER (PARTITION BY O.GRUPOPARTIC ORDER BY SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) DESC )  AS RANK_TIGRE_CC 

FROM TGFCAB C, TGFPAR P, TGFPRO PR, TGFTOP T, AD_OBJETIVOSRMD O 

WHERE 
P.FORNECEDOR = 'S' 
AND P.RAZAOSOCIAL LIKE '%TIGRE%' 
AND (PR.DESCRPROD LIKE '%TORNEIRA%' OR PR.DESCRPROD LIKE '%PINCEL%')
AND TRUNC(C.DTFATUR) BETWEEN '01/05/2019' AND '30/09/2019'   /* ALTERAR PERIODO DA CAMPANHA  */
AND T.GOLSINAL=-1
AND C.STATUSNOTA='L'
AND O.CODCAMP=18 

AND P.CODPARC=PR.CODPARCFORN 
AND O.CODPARTIC=C.CODPARC 
AND T.CODTIPOPER=C.CODTIPOPER 
AND T.DHALTER=C.DHTIPOPER 

GROUP BY 
C.CODPARC, 
O.GRUPOPARTIC 
/* *******  FIM: APURACAO 2 TORNEIRAS E PINCEIS */
) ON CODPARC_TIGRE_CC=PAR.CODPARC 

, AD_OBJETIVOSRMD OBJ

WHERE

PAR.DTCAD <= '31/05/2019'
AND OBJ.CODCAMP=18 

AND OBJ.CODPARTIC=PAR.CODPARC

ORDER BY PAR.CODPARC; 
