/* ************** LEVANTAMENTO DE DADOS - PREMIA CLIENTES */
SELECT 

-- CAMPOS DEFAULT
PAR.CODPARC, 
PAR.RAZAOSOCIAL, 
PAR.CODVEND, 

-- CAMPOS 1 PREMIO
GRP_RMD_PRM,
OBJ_RMD_PRM,
NVL(FAT_RMD_PRM, 0) AS FAT_RMD_PRM,
(CASE 
    WHEN NVL(FAT_RMD_PRM, 0) < OBJ_RMD_PRM THEN OBJ_RMD_PRM - NVL(FAT_RMD_PRM, 0)
ELSE
    (CASE WHEN NVL(FAT_RMD_PRM, 0) > OBJ_RMD_PRM THEN 0 END) 
END) AS QNT_FALTA_RMD_PRM, 

(CASE 
    WHEN (ROUND(((NVL(FAT_RMD_PRM, 0) / OBJ_RMD_PRM) * 100), 2) > 100) THEN 100 
ELSE 
    (ROUND(((NVL(FAT_RMD_PRM, 0) / OBJ_RMD_PRM) * 100), 2)) 
END) AS PERCENT_RMD_PRM, 

/* **************  CAMPOS 2 PREMIO               */
GRP_TIGRE_PRM, 
OBJ_TIGRE_PRM, 
NVL(FAT_TIGRE_PRM, 0) AS FAT_TIGRE_PRM, 
(CASE 
    WHEN NVL(FAT_TIGRE_PRM, 0) < OBJ_TIGRE_PRM THEN OBJ_TIGRE_PRM - NVL(FAT_TIGRE_PRM, 0)
ELSE
    (CASE WHEN NVL(FAT_TIGRE_PRM, 0) > OBJ_TIGRE_PRM THEN 0 END) 
END) AS QNT_FALTA_TIGRE_PRM, 

(CASE 
    WHEN (ROUND(((NVL(FAT_TIGRE_PRM, 0) / OBJ_TIGRE_PRM) * 100), 2) > 100) THEN 100 
ELSE 
    (ROUND(((NVL(FAT_TIGRE_PRM, 0) / OBJ_TIGRE_PRM) * 100), 2)) 
END) AS PERCENT_TIGRE_PRM 

FROM TGFPAR PAR 

LEFT JOIN 
(
/* **************  APURACAO 1 PREMIO              */
SELECT

C.CODPARC AS CODPARC_RMD_PRM,
O.GRUPOPARTIC AS GRP_RMD_PRM,
O.OBJ1 AS OBJ_RMD_PRM,
SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) AS FAT_RMD_PRM

FROM TGFCAB C, TGFTOP T, AD_OBJETIVOSRMD O

WHERE 
TRUNC(C.DTFATUR) BETWEEN '01/07/2019' AND '21/12/2019' 
AND T.GOLSINAL=-1
AND C.STATUSNOTA='L'
AND O.CODCAMP=18 

AND O.CODPARTIC=C.CODPARC
AND T.CODTIPOPER=C.CODTIPOPER
AND T.DHALTER=C.DHTIPOPER

AND C.CODPARC=2 /** RETIRAR **/

GROUP BY 
C.CODPARC,
O.GRUPOPARTIC,
O.OBJ1
/* **************  FIM: APURACAO 1 PREMIO         */
) ON CODPARC_RMD_PRM=PAR.CODPARC 

LEFT JOIN 
(
/* **************  APURACAO 2 PREMIO            */
SELECT 

C.CODPARC AS CODPARC_TIGRE_PRM, 
O.GRUPOPARTIC AS GRP_TIGRE_PRM, 
O.OBJ1 AS OBJ_TIGRE_PRM, 
SUM((C.VLRNOTA - C.VLRSUBST) * T.GOLDEV) AS FAT_TIGRE_PRM 

FROM TGFCAB C, TGFPAR P, TGFTOP T, AD_OBJETIVOSRMD O 

WHERE 
P.FORNECEDOR = 'S' 
AND P.RAZAOSOCIAL LIKE '%TIGRE%' 
AND TRUNC(C.DTFATUR) BETWEEN '01/07/2019' AND '21/12/2019' 
AND T.GOLSINAL=-1
AND C.STATUSNOTA='L'
AND O.CODCAMP=19 

AND O.CODPARTIC=C.CODPARC
AND T.CODTIPOPER=C.CODTIPOPER
AND T.DHALTER=C.DHTIPOPER

AND C.CODPARC=2 /** RETIRAR **/

GROUP BY 
C.CODPARC,
O.GRUPOPARTIC,
O.OBJ1
/* **************  FIM: APURACAO 2 PREMIO       */
) ON CODPARC_TIGRE_PRM=PAR.CODPARC 

, AD_OBJETIVOSRMD OBJ

WHERE

PAR.DTCAD <= '31/05/2019'
AND OBJ.CODCAMP=18 

AND OBJ.CODPARTIC=PAR.CODPARC

ORDER BY PAR.CODPARC; 
